"""Ajout de default_price

Revision ID: e7bd9fbc0335
Revises: 8daa857ad7b0
Create Date: 2025-04-22 18:12:18.205745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7bd9fbc0335'
down_revision = '8daa857ad7b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nova_pharma_product')
    op.drop_table('nova_pharma_sale')
    op.drop_table('eric_favre_product')
    op.drop_table('trois_chene_product')
    op.drop_table('gilbert_product')
    op.drop_table('eric_favre_sale')
    op.drop_table('gilbert_sale')
    op.drop_table('trois_chene_sale')
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_price', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('default_price')

    op.create_table('trois_chene_sale',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('product_id', sa.INTEGER(), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('price', sa.FLOAT(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('commercial_id', sa.INTEGER(), nullable=False),
    sa.Column('project', sa.VARCHAR(length=50), nullable=False),
    sa.ForeignKeyConstraint(['commercial_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['trois_chene_product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gilbert_sale',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('product_id', sa.INTEGER(), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('price', sa.FLOAT(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('commercial_id', sa.INTEGER(), nullable=False),
    sa.Column('project', sa.VARCHAR(length=50), nullable=False),
    sa.ForeignKeyConstraint(['commercial_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['gilbert_product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eric_favre_sale',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('product_id', sa.INTEGER(), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('price', sa.FLOAT(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('commercial_id', sa.INTEGER(), nullable=False),
    sa.Column('project', sa.VARCHAR(length=50), nullable=False),
    sa.ForeignKeyConstraint(['commercial_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['eric_favre_product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gilbert_product',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('default_price', sa.FLOAT(), nullable=False),
    sa.Column('stock_duopharm', sa.INTEGER(), nullable=False),
    sa.Column('stock_ubipharm', sa.INTEGER(), nullable=False),
    sa.Column('stock_laborex', sa.INTEGER(), nullable=False),
    sa.Column('stock_sodipharm', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trois_chene_product',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('default_price', sa.FLOAT(), nullable=False),
    sa.Column('stock_duopharm', sa.INTEGER(), nullable=False),
    sa.Column('stock_ubipharm', sa.INTEGER(), nullable=False),
    sa.Column('stock_laborex', sa.INTEGER(), nullable=False),
    sa.Column('stock_sodipharm', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eric_favre_product',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('default_price', sa.FLOAT(), nullable=False),
    sa.Column('stock_duopharm', sa.INTEGER(), nullable=False),
    sa.Column('stock_ubipharm', sa.INTEGER(), nullable=False),
    sa.Column('stock_laborex', sa.INTEGER(), nullable=False),
    sa.Column('stock_sodipharm', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nova_pharma_sale',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('product_id', sa.INTEGER(), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('price', sa.FLOAT(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('commercial_id', sa.INTEGER(), nullable=False),
    sa.Column('project', sa.VARCHAR(length=50), nullable=False),
    sa.ForeignKeyConstraint(['commercial_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['nova_pharma_product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nova_pharma_product',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('default_price', sa.FLOAT(), nullable=False),
    sa.Column('stock_duopharm', sa.INTEGER(), nullable=False),
    sa.Column('stock_ubipharm', sa.INTEGER(), nullable=False),
    sa.Column('stock_laborex', sa.INTEGER(), nullable=False),
    sa.Column('stock_sodipharm', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
